### ISSUE TITLE
Unexpected token import in existing project

### ISSUE THREAD

**Issue by bitTal** [Vizzuality/rails-redux-scaffold#6]
Once added all gems, package.json, .babelrc("presets": ["es2015", "react", "stage-2"]) and so on to an existent rails project; re-installed and started the server, the error 'Unexpected token import' was shown.

**Comment by davidsingal** [comment]
Do you get to sort out this issue? could yo write more details about this issue? @geriux @j8seangel @clementprdhomme do you have this issue too?

**Comment by bitTal** [comment]
This issue was fixed by clearing the cache:
  $ rake tmp:cache:clear
and restarting the server.
